version: 2.0

defaults: &defaults

  working_directory: /home/circleci/project

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

references:
  container_config: &container_config
    docker:
      - image: docker:17.11.0-ce-git

  dockerhub_login: &dockerhub_login
    - run:
        name: DockerHub Login
        command: |
          docker login -u ${DOCKERHUB_LOGIN} -p ${DOCKERHUB_PASS}

jobs:
  build_docker_image:
    <<: *defaults
    <<: *container_config

    steps:
      - checkout
      - run:
          name: Generate repository cache key
          command: |
            echo "export REPO_CACHE_KEY=$(git describe --always)" >> ${BASH_ENV}
      - run:
          name: Build Horizon Docker Image
          command: |
            echo "This is build_docker_image"
            pwd
      - run:
          name: Generate some files
          command: |
            echo "huhu" >> test.txt
      - run:
          name: Commit change
          command: |
            git commit -am "Release commit note"
            git push
      - run:
          name: Check REPO_CACHE_KEY
          command: |
            echo ${REPO_CACHE_KEY}
      - save_cache:
          key: ${REPO_CACHE_KEY}
          paths:
            - ./

  publish_dockerhub:
    <<: *defaults
    <<: *container_config

    steps:
      - restore_cache:
          key: ${REPO_CACHE_KEY}
      - run:
          name: Publish and Release
          command: |
            echo "This is publish and release"
      - run:
          name: Check cached content
          command: |
            ls -l
            cat test.txt

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docker_image
      - publish_dockerhub:
          requires:
            - build_docker_image
